<?php

/**
 * Rebuild PostgreSQL schema + seed from the local SQLite database.
 * Run from backend/: php database/sql/export-postgresql.php
 */

$sqlite = dirname(__DIR__, 2).'/database/database.sqlite';
$outDir = __DIR__.'/postgresql';
if (! is_dir($outDir) && ! mkdir($outDir, 0775, true) && ! is_dir($outDir)) {
    fwrite(STDERR, "Cannot create {$outDir}\n");
    exit(1);
}

$db = new PDO('sqlite:'.$sqlite);
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$skipData = [
    'personal_access_tokens',
    'sessions',
    'cache',
    'cache_locks',
    'jobs',
    'job_batches',
    'failed_jobs',
    'activity_logs',
    'login_sessions',
    'password_reset_tokens',
    'attendance_days',
    'attendance_events',
    'work_presences',
    'daily_reports',
];

$jsonColumns = [
    'companies' => ['settings'],
    'activity_logs' => ['old_values', 'new_values'],
    'personal_access_tokens' => ['abilities'],
];

$tables = $db->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")->fetchAll(PDO::FETCH_COLUMN);

$schema = [];
$schema[] = '-- Virtual Company OS — PostgreSQL schema';
$schema[] = '-- Generated from the Laravel migrations. Load into an empty database.';
$schema[] = '-- psql -d virtual_company -f 01_schema.sql';
$schema[] = 'BEGIN;';
$schema[] = '';

$foreignKeys = [];
$indexes = [];

foreach ($tables as $table) {
    $columns = $db->query('PRAGMA table_info('.$db->quote($table).')')->fetchAll(PDO::FETCH_ASSOC);
    $lines = [];
    $pk = [];
    foreach ($columns as $column) {
        $name = $column['name'];
        $type = mapType($column['type'], $table, $name, $jsonColumns);
        $line = '    '.$name.' '.$type;
        if ((int) $column['pk'] === 1 && count(array_filter($columns, fn ($c) => (int) $c['pk'] > 0)) === 1 && $type === 'bigint') {
            $line .= ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        } elseif ((int) $column['pk'] > 0) {
            $pk[] = $name;
        }
        if ((int) $column['notnull'] === 1 && ! str_contains($line, 'PRIMARY KEY')) {
            $line .= ' NOT NULL';
        }
        if ($column['dflt_value'] !== null && ! str_contains($line, 'PRIMARY KEY')) {
            $line .= ' DEFAULT '.mapDefault((string) $column['dflt_value'], $type);
        }
        $lines[] = $line;
    }
    if ($pk !== []) {
        $lines[] = '    PRIMARY KEY ('.implode(', ', $pk).')';
    }
    $schema[] = 'CREATE TABLE '.$table.' (';
    $schema[] = implode(",\n", $lines);
    $schema[] = ');';
    $schema[] = '';

    foreach ($db->query('PRAGMA foreign_key_list('.$db->quote($table).')')->fetchAll(PDO::FETCH_ASSOC) as $fk) {
        $action = strtoupper((string) $fk['on_delete']);
        $action = $action === 'SET NULL' ? 'SET NULL' : ($action === 'CASCADE' ? 'CASCADE' : 'NO ACTION');
        $foreignKeys[] = sprintf(
            'ALTER TABLE %s ADD CONSTRAINT %s_%s_fk FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s;',
            $table,
            $table,
            $fk['from'],
            $fk['from'],
            $fk['table'],
            $fk['to'],
            $action,
        );
    }
}

foreach ($db->query("SELECT sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL") as $row) {
    $sql = (string) $row['sql'];
    $sql = preg_replace('/^CREATE UNIQUE INDEX/i', 'CREATE UNIQUE INDEX', $sql) ?? $sql;
    $sql = preg_replace('/^CREATE INDEX/i', 'CREATE INDEX', $sql) ?? $sql;
    $indexes[] = rtrim($sql, ';').';';
}

$schema[] = implode("\n", $foreignKeys);
$schema[] = '';
$schema[] = implode("\n", $indexes);
$schema[] = '';
$schema[] = 'COMMIT;';
$schema[] = '';

file_put_contents($outDir.'/01_schema.sql', implode("\n", $schema));

$seed = [];
$seed[] = '-- Virtual Company OS — default company, roles, login accounts, sample projects, and HR.';
$seed[] = '-- Password for every account: ChangeMe!2026';
$seed[] = '-- Change it before any shared or production use.';
$seed[] = '-- hr_profiles in this file contains a fake national id and salary. Treat the file as sensitive.';
$seed[] = 'BEGIN;';
$seed[] = '';

$seedOrder = [
    'migrations',
    'users',
    'permissions',
    'companies',
    'departments',
    'company_user',
    'teams',
    'team_user',
    'roles',
    'role_permissions',
    'user_roles',
    'user_permissions',
    'work_schedules',
    'features',
    'settings',
    'projects',
    'project_members',
    'kanban_columns',
    'tasks',
    'task_comments',
    'hr_profiles',
    'leave_requests',
    'mission_requests',
    'channels',
    'channel_members',
    'messages',
    'announcements',
    'events',
    'crm_accounts',
    'crm_contacts',
    'crm_deals',
    'campaigns',
    'invoices',
    'expenses',
    'tickets',
    'ticket_messages',
    'approvals',
    'documents',
];

foreach ($seedOrder as $table) {
    if (in_array($table, $skipData, true)) {
        continue;
    }
    $columns = $db->query('PRAGMA table_info('.$db->quote($table).')')->fetchAll(PDO::FETCH_ASSOC);
    $names = array_column($columns, 'name');
    $rows = $db->query('SELECT * FROM '.$table)->fetchAll(PDO::FETCH_ASSOC);
    if ($rows === []) {
        continue;
    }
    $seed[] = '-- '.$table;
    foreach (array_chunk($rows, 50) as $chunk) {
        $seed[] = 'INSERT INTO '.$table.' ('.implode(', ', $names).') VALUES';
        $values = [];
        foreach ($chunk as $row) {
            $cells = [];
            foreach ($names as $name) {
                $cells[] = literal($row[$name], columnType($columns, $name), in_array($name, $jsonColumns[$table] ?? [], true));
            }
            $values[] = '    ('.implode(', ', $cells).')';
        }
        $seed[] = implode(",\n", $values).';';
        $seed[] = '';
    }
    $hasId = in_array('id', $names, true);
    if ($hasId) {
        $seed[] = "SELECT setval(pg_get_serial_sequence('{$table}', 'id'), COALESCE((SELECT MAX(id) FROM {$table}), 1), true);";
        $seed[] = '';
    }
}

$seed[] = 'COMMIT;';
$seed[] = '';
file_put_contents($outDir.'/02_seed.sql', implode("\n", $seed));

$attendance = <<<'SQL'
-- Sample attendance for today in Asia/Tehran.
-- Safe to skip if you only need the accounts in 02_seed.sql.
BEGIN;

INSERT INTO attendance_days (
    company_id, uuid, user_id, work_date, location, day_status,
    check_in_at, late_minutes, worked_minutes, break_minutes, expected_minutes,
    excused, note, created_at, updated_at
)
SELECT c.id, gen_random_uuid()::text, u.id, (timezone('Asia/Tehran', now()))::date,
       'office', 'open',
       ((date_trunc('day', timezone('Asia/Tehran', now())) + time '08:50') AT TIME ZONE 'Asia/Tehran') AT TIME ZONE 'UTC',
       0, 0, 0, 420, false, 'شروع روز در دفتر', now(), now()
FROM users u
JOIN company_user cu ON cu.user_id = u.id
JOIN companies c ON c.id = cu.company_id AND c.slug = 'ideban-almas'
WHERE u.email = 'ceo@ideban.test'
ON CONFLICT (company_id, user_id, work_date) DO NOTHING;

INSERT INTO attendance_days (
    company_id, uuid, user_id, work_date, location, day_status,
    check_in_at, late_minutes, worked_minutes, break_minutes, expected_minutes,
    excused, note, created_at, updated_at
)
SELECT c.id, gen_random_uuid()::text, u.id, (timezone('Asia/Tehran', now()))::date,
       'remote', 'open',
       ((date_trunc('day', timezone('Asia/Tehran', now())) + time '09:05') AT TIME ZONE 'Asia/Tehran') AT TIME ZONE 'UTC',
       0, 0, 0, 420, false, NULL, now(), now()
FROM users u
JOIN company_user cu ON cu.user_id = u.id
JOIN companies c ON c.id = cu.company_id AND c.slug = 'ideban-almas'
WHERE u.email = 'developer@ideban.test'
ON CONFLICT (company_id, user_id, work_date) DO NOTHING;

INSERT INTO work_presences (company_id, user_id, status, note, since, created_at, updated_at)
SELECT c.id, u.id, 'office', 'شروع روز در دفتر', now(), now(), now()
FROM users u
JOIN company_user cu ON cu.user_id = u.id
JOIN companies c ON c.id = cu.company_id AND c.slug = 'ideban-almas'
WHERE u.email = 'ceo@ideban.test'
ON CONFLICT (company_id, user_id) DO NOTHING;

INSERT INTO work_presences (company_id, user_id, status, since, created_at, updated_at)
SELECT c.id, u.id, 'remote', now(), now(), now()
FROM users u
JOIN company_user cu ON cu.user_id = u.id
JOIN companies c ON c.id = cu.company_id AND c.slug = 'ideban-almas'
WHERE u.email = 'developer@ideban.test'
ON CONFLICT (company_id, user_id) DO NOTHING;

INSERT INTO daily_reports (company_id, uuid, user_id, work_date, kind, body, submitted_at, created_at, updated_at)
SELECT c.id, gen_random_uuid()::text, u.id, (timezone('Asia/Tehran', now()))::date, 'morning',
       'امروز روی محصول و گزارش روزانه کار می‌کنم.', now(), now(), now()
FROM users u
JOIN company_user cu ON cu.user_id = u.id
JOIN companies c ON c.id = cu.company_id AND c.slug = 'ideban-almas'
WHERE u.email = 'developer@ideban.test'
ON CONFLICT (company_id, user_id, work_date, kind) DO NOTHING;

SELECT setval(pg_get_serial_sequence('attendance_days', 'id'), COALESCE((SELECT MAX(id) FROM attendance_days), 1), true);
SELECT setval(pg_get_serial_sequence('work_presences', 'id'), COALESCE((SELECT MAX(id) FROM work_presences), 1), true);
SELECT setval(pg_get_serial_sequence('daily_reports', 'id'), COALESCE((SELECT MAX(id) FROM daily_reports), 1), true);

COMMIT;
SQL;

file_put_contents($outDir.'/03_demo_attendance.sql', $attendance."\n");

fwrite(STDOUT, "Wrote {$outDir}\n");

function mapType(string $raw, string $table, string $column, array $jsonColumns): string
{
    $type = strtolower(trim($raw));
    if (in_array($column, $jsonColumns[$table] ?? [], true)) {
        return 'jsonb';
    }
    if (str_contains($type, 'tinyint(1)')) {
        return 'boolean';
    }
    if (str_starts_with($type, 'varchar') || $type === 'varchar') {
        return 'varchar(255)';
    }
    if ($type === 'text') {
        return 'text';
    }
    if ($type === 'date') {
        return 'date';
    }
    if ($type === 'time') {
        return 'time';
    }
    if ($type === 'datetime' || str_contains($type, 'timestamp')) {
        return 'timestamp';
    }
    if (str_contains($type, 'int')) {
        return 'bigint';
    }

    return 'text';
}

function mapDefault(string $default, string $type): string
{
    $default = trim($default);
    if (preg_match("/^'(.*)'$/s", $default, $match)) {
        $default = str_replace("''", "'", $match[1]);
    }
    $default = trim($default, "()");
    if (strtoupper($default) === 'CURRENT_TIMESTAMP') {
        return 'CURRENT_TIMESTAMP';
    }
    if ($type === 'boolean') {
        return in_array($default, ['1', 'true'], true) ? 'true' : 'false';
    }
    if ($type === 'bigint') {
        return (string) (int) $default;
    }
    if ($type === 'time') {
        return "'".str_replace("'", "''", $default)."'";
    }

    return "'".str_replace("'", "''", $default)."'";
}

function columnType(array $columns, string $name): string
{
    foreach ($columns as $column) {
        if ($column['name'] === $name) {
            return strtolower((string) $column['type']);
        }
    }

    return 'text';
}

function literal(mixed $value, string $sqliteType, bool $json): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (str_contains($sqliteType, 'tinyint(1)')) {
        return ((string) $value === '1' || $value === 1 || $value === true) ? 'true' : 'false';
    }
    if (is_int($value) || (is_string($value) && preg_match('/^-?\d+$/', $value) && str_contains($sqliteType, 'int') && ! str_contains($sqliteType, 'tinyint(1)'))) {
        return (string) $value;
    }
    $text = (string) $value;
    if ($json) {
        return "'".str_replace("'", "''", $text)."'::jsonb";
    }

    return "'".str_replace("'", "''", $text)."'";
}
