-- Virtual Company OS — PostgreSQL schema
-- Generated from the Laravel migrations. Load into an empty database.
-- psql -d virtual_company -f 01_schema.sql
BEGIN;

CREATE TABLE activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint,
    user_id bigint,
    action varchar(255) NOT NULL,
    entity_type varchar(255),
    entity_id bigint,
    entity_uuid varchar(255),
    description varchar(255),
    old_values jsonb,
    new_values jsonb,
    ip varchar(255),
    user_agent text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    body text NOT NULL,
    author_id bigint,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    kind varchar(255) NOT NULL DEFAULT 'general',
    status varchar(255) NOT NULL DEFAULT 'pending',
    requester_id bigint NOT NULL,
    reviewer_id bigint,
    note text,
    review_note text,
    reviewed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE attendance_days (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    work_date date NOT NULL,
    location varchar(255) NOT NULL DEFAULT 'office',
    day_status varchar(255) NOT NULL DEFAULT 'marked',
    check_in_at timestamp,
    check_out_at timestamp,
    late_minutes bigint NOT NULL DEFAULT 0,
    worked_minutes bigint NOT NULL DEFAULT 0,
    break_minutes bigint NOT NULL DEFAULT 0,
    expected_minutes bigint NOT NULL DEFAULT 0,
    excused boolean NOT NULL DEFAULT false,
    note text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE attendance_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    attendance_day_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type varchar(255) NOT NULL,
    occurred_at timestamp NOT NULL,
    location varchar(255),
    status varchar(255),
    note text,
    source varchar(255) NOT NULL DEFAULT 'self',
    actor_id bigint,
    ip varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE cache (
    key varchar(255) NOT NULL,
    value text NOT NULL,
    expiration bigint NOT NULL,
    PRIMARY KEY (key)
);

CREATE TABLE cache_locks (
    key varchar(255) NOT NULL,
    owner varchar(255) NOT NULL,
    expiration bigint NOT NULL,
    PRIMARY KEY (key)
);

CREATE TABLE campaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    channel varchar(255) NOT NULL DEFAULT 'social',
    status varchar(255) NOT NULL DEFAULT 'draft',
    budget_amount text,
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    starts_on date,
    ends_on date,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE channel_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    channel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    kind varchar(255) NOT NULL DEFAULT 'company',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    legal_name varchar(255),
    slug varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'active',
    timezone varchar(255) NOT NULL DEFAULT 'Asia/Tehran',
    locale varchar(255) NOT NULL DEFAULT 'fa',
    logo_path varchar(255),
    plan varchar(255),
    user_limit bigint,
    settings jsonb,
    onboarded_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE company_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL,
    department_id bigint,
    job_title varchar(255),
    employee_code varchar(255),
    status varchar(255) NOT NULL DEFAULT 'active',
    is_owner boolean NOT NULL DEFAULT false,
    joined_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE crm_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE crm_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    account_id bigint,
    name varchar(255) NOT NULL,
    email varchar(255),
    phone varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE crm_deals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    account_id bigint,
    title varchar(255) NOT NULL,
    stage varchar(255) NOT NULL DEFAULT 'lead',
    amount text NOT NULL DEFAULT '0',
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    owner_id bigint,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    name varchar(255) NOT NULL,
    quantity bigint NOT NULL,
    unit_price text NOT NULL,
    line_total text NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    customer_id bigint NOT NULL,
    number varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'submitted',
    note text,
    staff_note text,
    total_amount text NOT NULL DEFAULT '0',
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    reviewer_id bigint,
    reviewed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_thread_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    thread_id bigint NOT NULL,
    user_id bigint NOT NULL,
    body text NOT NULL,
    is_staff boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_threads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    customer_id bigint NOT NULL,
    desk varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'open',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_ticket_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    user_id bigint NOT NULL,
    body text NOT NULL,
    is_staff boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customer_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    customer_id bigint NOT NULL,
    number varchar(255) NOT NULL,
    desk varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    priority varchar(255) NOT NULL DEFAULT 'normal',
    status varchar(255) NOT NULL DEFAULT 'open',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'pending',
    organization_name varchar(255),
    phone varchar(255),
    note text,
    review_note text,
    reviewer_id bigint,
    reviewed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE daily_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    work_date date NOT NULL,
    kind varchar(255) NOT NULL,
    body text NOT NULL,
    blockers text,
    submitted_at timestamp NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    code varchar(255),
    description text,
    manager_id bigint,
    parent_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    sort_order bigint NOT NULL DEFAULT 0,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    body text NOT NULL,
    visibility varchar(255) NOT NULL DEFAULT 'company',
    author_id bigint,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    location varchar(255),
    starts_at timestamp NOT NULL,
    ends_at timestamp NOT NULL,
    visibility varchar(255) NOT NULL DEFAULT 'company',
    owner_id bigint,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    amount text NOT NULL,
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    status varchar(255) NOT NULL DEFAULT 'recorded',
    spent_on date,
    note varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE failed_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL,
    connection varchar(255) NOT NULL,
    queue varchar(255) NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE features (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    key varchar(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE hr_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL,
    hire_date date,
    employment_type varchar(255),
    national_id varchar(255),
    emergency_name varchar(255),
    emergency_phone varchar(255),
    salary_amount text,
    salary_currency varchar(255) NOT NULL DEFAULT 'IRR',
    notes text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    name varchar(255),
    role_id bigint,
    department_id bigint,
    team_id bigint,
    token varchar(255) NOT NULL,
    invited_by bigint,
    expires_at timestamp NOT NULL,
    accepted_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    number varchar(255) NOT NULL,
    party_name varchar(255) NOT NULL,
    amount text NOT NULL,
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    status varchar(255) NOT NULL DEFAULT 'draft',
    issued_on date,
    due_on date,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE job_batches (
    id varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    total_jobs bigint NOT NULL,
    pending_jobs bigint NOT NULL,
    failed_jobs bigint NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at bigint,
    created_at bigint NOT NULL,
    finished_at bigint,
    PRIMARY KEY (id)
);

CREATE TABLE jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue varchar(255) NOT NULL,
    payload text NOT NULL,
    attempts bigint NOT NULL,
    reserved_at bigint,
    available_at bigint NOT NULL,
    created_at bigint NOT NULL
);

CREATE TABLE kanban_columns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    project_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    sort_order bigint NOT NULL DEFAULT 0,
    is_done boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    type varchar(255) NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    reason text NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'pending',
    reviewer_id bigint,
    reviewed_at timestamp,
    review_note text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE login_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    company_id bigint,
    token_id bigint,
    ip varchar(255),
    user_agent text,
    device varchar(255),
    logged_in_at timestamp NOT NULL,
    logged_out_at timestamp,
    last_activity_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    channel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    body text NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration varchar(255) NOT NULL,
    batch bigint NOT NULL
);

CREATE TABLE mission_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    destination varchar(255) NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    purpose text NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'pending',
    reviewer_id bigint,
    reviewed_at timestamp,
    review_note text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE password_reset_tokens (
    email varchar(255) NOT NULL,
    token varchar(255) NOT NULL,
    created_at timestamp,
    PRIMARY KEY (email)
);

CREATE TABLE permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    module varchar(255) NOT NULL,
    description varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE personal_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type varchar(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name text NOT NULL,
    token varchar(255) NOT NULL,
    abilities jsonb,
    last_used_at timestamp,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    company_id bigint
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    sku varchar(255),
    description text,
    unit_price text NOT NULL DEFAULT '0',
    currency varchar(255) NOT NULL DEFAULT 'IRR',
    stock bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE project_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role varchar(255) NOT NULL DEFAULT 'member',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    code varchar(255),
    description text,
    status varchar(255) NOT NULL DEFAULT 'active',
    visibility varchar(255) NOT NULL DEFAULT 'company',
    department_id bigint,
    owner_id bigint,
    start_date date,
    due_date date,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description varchar(255),
    is_system boolean NOT NULL DEFAULT false,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE sessions (
    id varchar(255) NOT NULL,
    user_id bigint,
    ip_address varchar(255),
    user_agent text,
    payload text NOT NULL,
    last_activity bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    key varchar(255) NOT NULL,
    value text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE task_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    task_id bigint NOT NULL,
    user_id bigint,
    uuid varchar(255) NOT NULL,
    body text NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    project_id bigint NOT NULL,
    column_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    priority varchar(255) NOT NULL DEFAULT 'normal',
    assignee_id bigint,
    reporter_id bigint,
    due_date date,
    sort_order bigint NOT NULL DEFAULT 0,
    completed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE team_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role varchar(255) NOT NULL DEFAULT 'member',
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    department_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description text,
    leader_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE ticket_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    user_id bigint,
    uuid varchar(255) NOT NULL,
    body text NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    body text NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'open',
    priority varchar(255) NOT NULL DEFAULT 'normal',
    requester_id bigint NOT NULL,
    assignee_id bigint,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(255),
    avatar_path varchar(255),
    locale varchar(255) NOT NULL DEFAULT 'fa',
    timezone varchar(255),
    status varchar(255) NOT NULL DEFAULT 'active',
    is_platform_admin boolean NOT NULL DEFAULT false,
    email_verified_at timestamp,
    password varchar(255) NOT NULL,
    last_login_at timestamp,
    last_login_ip varchar(255),
    two_factor_secret text,
    two_factor_recovery_codes text,
    two_factor_confirmed_at timestamp,
    remember_token varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE work_presences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'off',
    resume_status varchar(255),
    note text,
    since timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE work_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    weekday bigint NOT NULL,
    is_working_day boolean NOT NULL DEFAULT true,
    start_time time NOT NULL DEFAULT '09:00',
    end_time time NOT NULL DEFAULT '17:00',
    break_minutes bigint NOT NULL DEFAULT 60,
    grace_minutes bigint NOT NULL DEFAULT 15,
    created_at timestamp,
    updated_at timestamp
);

ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL;
ALTER TABLE announcements ADD CONSTRAINT announcements_author_id_fk FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE announcements ADD CONSTRAINT announcements_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE approvals ADD CONSTRAINT approvals_reviewer_id_fk FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE approvals ADD CONSTRAINT approvals_requester_id_fk FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE approvals ADD CONSTRAINT approvals_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE attendance_days ADD CONSTRAINT attendance_days_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE attendance_days ADD CONSTRAINT attendance_days_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE attendance_events ADD CONSTRAINT attendance_events_actor_id_fk FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE attendance_events ADD CONSTRAINT attendance_events_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE attendance_events ADD CONSTRAINT attendance_events_attendance_day_id_fk FOREIGN KEY (attendance_day_id) REFERENCES attendance_days (id) ON DELETE CASCADE;
ALTER TABLE attendance_events ADD CONSTRAINT attendance_events_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE campaigns ADD CONSTRAINT campaigns_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE channel_members ADD CONSTRAINT channel_members_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE channel_members ADD CONSTRAINT channel_members_channel_id_fk FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;
ALTER TABLE channel_members ADD CONSTRAINT channel_members_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE channels ADD CONSTRAINT channels_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE company_user ADD CONSTRAINT company_user_department_id_fk FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE company_user ADD CONSTRAINT company_user_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE company_user ADD CONSTRAINT company_user_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE crm_accounts ADD CONSTRAINT crm_accounts_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE crm_contacts ADD CONSTRAINT crm_contacts_account_id_fk FOREIGN KEY (account_id) REFERENCES crm_accounts (id) ON DELETE SET NULL;
ALTER TABLE crm_contacts ADD CONSTRAINT crm_contacts_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE crm_deals ADD CONSTRAINT crm_deals_owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE crm_deals ADD CONSTRAINT crm_deals_account_id_fk FOREIGN KEY (account_id) REFERENCES crm_accounts (id) ON DELETE SET NULL;
ALTER TABLE crm_deals ADD CONSTRAINT crm_deals_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_order_items ADD CONSTRAINT customer_order_items_product_id_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL;
ALTER TABLE customer_order_items ADD CONSTRAINT customer_order_items_order_id_fk FOREIGN KEY (order_id) REFERENCES customer_orders (id) ON DELETE CASCADE;
ALTER TABLE customer_order_items ADD CONSTRAINT customer_order_items_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_orders ADD CONSTRAINT customer_orders_reviewer_id_fk FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE customer_orders ADD CONSTRAINT customer_orders_customer_id_fk FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE;
ALTER TABLE customer_orders ADD CONSTRAINT customer_orders_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_thread_messages ADD CONSTRAINT customer_thread_messages_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE customer_thread_messages ADD CONSTRAINT customer_thread_messages_thread_id_fk FOREIGN KEY (thread_id) REFERENCES customer_threads (id) ON DELETE CASCADE;
ALTER TABLE customer_thread_messages ADD CONSTRAINT customer_thread_messages_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_threads ADD CONSTRAINT customer_threads_customer_id_fk FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE;
ALTER TABLE customer_threads ADD CONSTRAINT customer_threads_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_ticket_messages ADD CONSTRAINT customer_ticket_messages_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE customer_ticket_messages ADD CONSTRAINT customer_ticket_messages_ticket_id_fk FOREIGN KEY (ticket_id) REFERENCES customer_tickets (id) ON DELETE CASCADE;
ALTER TABLE customer_ticket_messages ADD CONSTRAINT customer_ticket_messages_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customer_tickets ADD CONSTRAINT customer_tickets_customer_id_fk FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE;
ALTER TABLE customer_tickets ADD CONSTRAINT customer_tickets_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customers ADD CONSTRAINT customers_reviewer_id_fk FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE customers ADD CONSTRAINT customers_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE customers ADD CONSTRAINT customers_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE daily_reports ADD CONSTRAINT daily_reports_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE daily_reports ADD CONSTRAINT daily_reports_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE departments ADD CONSTRAINT departments_parent_id_fk FOREIGN KEY (parent_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE departments ADD CONSTRAINT departments_manager_id_fk FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE departments ADD CONSTRAINT departments_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE documents ADD CONSTRAINT documents_author_id_fk FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE documents ADD CONSTRAINT documents_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE events ADD CONSTRAINT events_owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE events ADD CONSTRAINT events_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE expenses ADD CONSTRAINT expenses_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE features ADD CONSTRAINT features_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE hr_profiles ADD CONSTRAINT hr_profiles_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE hr_profiles ADD CONSTRAINT hr_profiles_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE invitations ADD CONSTRAINT invitations_invited_by_fk FOREIGN KEY (invited_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT invitations_team_id_fk FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT invitations_department_id_fk FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT invitations_role_id_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE SET NULL;
ALTER TABLE invitations ADD CONSTRAINT invitations_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE invoices ADD CONSTRAINT invoices_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE kanban_columns ADD CONSTRAINT kanban_columns_project_id_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE kanban_columns ADD CONSTRAINT kanban_columns_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_reviewer_id_fk FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE login_sessions ADD CONSTRAINT login_sessions_token_id_fk FOREIGN KEY (token_id) REFERENCES personal_access_tokens (id) ON DELETE SET NULL;
ALTER TABLE login_sessions ADD CONSTRAINT login_sessions_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL;
ALTER TABLE login_sessions ADD CONSTRAINT login_sessions_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_channel_id_fk FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE mission_requests ADD CONSTRAINT mission_requests_reviewer_id_fk FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE mission_requests ADD CONSTRAINT mission_requests_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE mission_requests ADD CONSTRAINT mission_requests_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE personal_access_tokens ADD CONSTRAINT personal_access_tokens_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL;
ALTER TABLE products ADD CONSTRAINT products_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE project_members ADD CONSTRAINT project_members_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE project_members ADD CONSTRAINT project_members_project_id_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE project_members ADD CONSTRAINT project_members_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE projects ADD CONSTRAINT projects_owner_id_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE projects ADD CONSTRAINT projects_department_id_fk FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;
ALTER TABLE projects ADD CONSTRAINT projects_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_permission_id_fk FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_role_id_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;
ALTER TABLE roles ADD CONSTRAINT roles_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE settings ADD CONSTRAINT settings_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE task_comments ADD CONSTRAINT task_comments_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE task_comments ADD CONSTRAINT task_comments_task_id_fk FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE;
ALTER TABLE task_comments ADD CONSTRAINT task_comments_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT tasks_reporter_id_fk FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_assignee_id_fk FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT tasks_column_id_fk FOREIGN KEY (column_id) REFERENCES kanban_columns (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT tasks_project_id_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT tasks_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE team_user ADD CONSTRAINT team_user_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE team_user ADD CONSTRAINT team_user_team_id_fk FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
ALTER TABLE teams ADD CONSTRAINT teams_leader_id_fk FOREIGN KEY (leader_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE teams ADD CONSTRAINT teams_department_id_fk FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE;
ALTER TABLE teams ADD CONSTRAINT teams_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE ticket_messages ADD CONSTRAINT ticket_messages_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE ticket_messages ADD CONSTRAINT ticket_messages_ticket_id_fk FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE;
ALTER TABLE ticket_messages ADD CONSTRAINT ticket_messages_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE tickets ADD CONSTRAINT tickets_assignee_id_fk FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE tickets ADD CONSTRAINT tickets_requester_id_fk FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE tickets ADD CONSTRAINT tickets_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_permission_id_fk FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_role_id_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE work_presences ADD CONSTRAINT work_presences_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE work_presences ADD CONSTRAINT work_presences_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE work_schedules ADD CONSTRAINT work_schedules_company_id_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX "users_uuid_unique" on "users" ("uuid");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "users_status_index" on "users" ("status");
CREATE INDEX "users_is_platform_admin_index" on "users" ("is_platform_admin");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE INDEX "failed_jobs_connection_queue_failed_at_index" on "failed_jobs" ("connection", "queue", "failed_at");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "companies_uuid_unique" on "companies" ("uuid");
CREATE UNIQUE INDEX "companies_slug_unique" on "companies" ("slug");
CREATE INDEX "companies_status_index" on "companies" ("status");
CREATE UNIQUE INDEX "departments_company_id_slug_unique" on "departments" ("company_id", "slug");
CREATE UNIQUE INDEX "departments_company_id_code_unique" on "departments" ("company_id", "code");
CREATE UNIQUE INDEX "departments_uuid_unique" on "departments" ("uuid");
CREATE UNIQUE INDEX "company_user_company_id_employee_code_unique" on "company_user" ("company_id", "employee_code");
CREATE UNIQUE INDEX "company_user_company_id_user_id_unique" on "company_user" ("company_id", "user_id");
CREATE INDEX "company_user_status_index" on "company_user" ("status");
CREATE UNIQUE INDEX "teams_company_id_slug_unique" on "teams" ("company_id", "slug");
CREATE UNIQUE INDEX "teams_uuid_unique" on "teams" ("uuid");
CREATE UNIQUE INDEX "team_user_team_id_user_id_unique" on "team_user" ("team_id", "user_id");
CREATE UNIQUE INDEX "permissions_name_unique" on "permissions" ("name");
CREATE INDEX "permissions_module_index" on "permissions" ("module");
CREATE UNIQUE INDEX "roles_company_id_slug_unique" on "roles" ("company_id", "slug");
CREATE UNIQUE INDEX "roles_uuid_unique" on "roles" ("uuid");
CREATE UNIQUE INDEX "user_roles_company_id_user_id_role_id_unique" on "user_roles" ("company_id", "user_id", "role_id");
CREATE UNIQUE INDEX "user_permissions_unique" on "user_permissions" ("company_id", "user_id", "permission_id");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "work_schedules_company_id_weekday_unique" on "work_schedules" ("company_id", "weekday");
CREATE INDEX "activity_logs_company_id_created_at_index" on "activity_logs" ("company_id", "created_at");
CREATE INDEX "activity_logs_action_index" on "activity_logs" ("action");
CREATE INDEX "activity_logs_created_at_index" on "activity_logs" ("created_at");
CREATE INDEX "invitations_company_id_email_index" on "invitations" ("company_id", "email");
CREATE UNIQUE INDEX "invitations_uuid_unique" on "invitations" ("uuid");
CREATE UNIQUE INDEX "invitations_token_unique" on "invitations" ("token");
CREATE INDEX "login_sessions_user_id_logged_out_at_index" on "login_sessions" ("user_id", "logged_out_at");
CREATE UNIQUE INDEX "login_sessions_uuid_unique" on "login_sessions" ("uuid");
CREATE UNIQUE INDEX "settings_company_id_key_unique" on "settings" ("company_id", "key");
CREATE UNIQUE INDEX "features_company_id_key_unique" on "features" ("company_id", "key");
CREATE UNIQUE INDEX "attendance_days_company_id_user_id_work_date_unique" on "attendance_days" ("company_id", "user_id", "work_date");
CREATE INDEX "attendance_days_company_id_work_date_index" on "attendance_days" ("company_id", "work_date");
CREATE UNIQUE INDEX "attendance_days_uuid_unique" on "attendance_days" ("uuid");
CREATE INDEX "attendance_events_company_id_user_id_occurred_at_index" on "attendance_events" ("company_id", "user_id", "occurred_at");
CREATE UNIQUE INDEX "attendance_events_uuid_unique" on "attendance_events" ("uuid");
CREATE UNIQUE INDEX "work_presences_company_id_user_id_unique" on "work_presences" ("company_id", "user_id");
CREATE UNIQUE INDEX "daily_reports_company_id_user_id_work_date_kind_unique" on "daily_reports" ("company_id", "user_id", "work_date", "kind");
CREATE UNIQUE INDEX "daily_reports_uuid_unique" on "daily_reports" ("uuid");
CREATE UNIQUE INDEX "projects_company_id_slug_unique" on "projects" ("company_id", "slug");
CREATE UNIQUE INDEX "projects_uuid_unique" on "projects" ("uuid");
CREATE INDEX "projects_status_index" on "projects" ("status");
CREATE UNIQUE INDEX "project_members_project_id_user_id_unique" on "project_members" ("project_id", "user_id");
CREATE UNIQUE INDEX "kanban_columns_uuid_unique" on "kanban_columns" ("uuid");
CREATE INDEX "tasks_company_id_assignee_id_due_date_index" on "tasks" ("company_id", "assignee_id", "due_date");
CREATE UNIQUE INDEX "tasks_uuid_unique" on "tasks" ("uuid");
CREATE UNIQUE INDEX "task_comments_uuid_unique" on "task_comments" ("uuid");
CREATE UNIQUE INDEX "hr_profiles_company_id_user_id_unique" on "hr_profiles" ("company_id", "user_id");
CREATE INDEX "leave_requests_company_id_user_id_status_index" on "leave_requests" ("company_id", "user_id", "status");
CREATE UNIQUE INDEX "leave_requests_uuid_unique" on "leave_requests" ("uuid");
CREATE INDEX "leave_requests_status_index" on "leave_requests" ("status");
CREATE INDEX "mission_requests_company_id_user_id_status_index" on "mission_requests" ("company_id", "user_id", "status");
CREATE UNIQUE INDEX "mission_requests_uuid_unique" on "mission_requests" ("uuid");
CREATE INDEX "mission_requests_status_index" on "mission_requests" ("status");
CREATE UNIQUE INDEX "channels_company_id_slug_unique" on "channels" ("company_id", "slug");
CREATE UNIQUE INDEX "channels_uuid_unique" on "channels" ("uuid");
CREATE UNIQUE INDEX "channel_members_channel_id_user_id_unique" on "channel_members" ("channel_id", "user_id");
CREATE INDEX "messages_channel_id_id_index" on "messages" ("channel_id", "id");
CREATE UNIQUE INDEX "messages_uuid_unique" on "messages" ("uuid");
CREATE UNIQUE INDEX "announcements_uuid_unique" on "announcements" ("uuid");
CREATE INDEX "events_company_id_starts_at_index" on "events" ("company_id", "starts_at");
CREATE UNIQUE INDEX "events_uuid_unique" on "events" ("uuid");
CREATE UNIQUE INDEX "crm_accounts_uuid_unique" on "crm_accounts" ("uuid");
CREATE UNIQUE INDEX "crm_contacts_uuid_unique" on "crm_contacts" ("uuid");
CREATE UNIQUE INDEX "crm_deals_uuid_unique" on "crm_deals" ("uuid");
CREATE UNIQUE INDEX "campaigns_uuid_unique" on "campaigns" ("uuid");
CREATE UNIQUE INDEX "invoices_company_id_number_unique" on "invoices" ("company_id", "number");
CREATE UNIQUE INDEX "invoices_uuid_unique" on "invoices" ("uuid");
CREATE UNIQUE INDEX "expenses_uuid_unique" on "expenses" ("uuid");
CREATE INDEX "tickets_company_id_status_index" on "tickets" ("company_id", "status");
CREATE UNIQUE INDEX "tickets_uuid_unique" on "tickets" ("uuid");
CREATE UNIQUE INDEX "ticket_messages_uuid_unique" on "ticket_messages" ("uuid");
CREATE UNIQUE INDEX "approvals_uuid_unique" on "approvals" ("uuid");
CREATE UNIQUE INDEX "documents_uuid_unique" on "documents" ("uuid");
CREATE UNIQUE INDEX "customers_company_id_user_id_unique" on "customers" ("company_id", "user_id");
CREATE INDEX "customers_company_id_status_index" on "customers" ("company_id", "status");
CREATE UNIQUE INDEX "customers_uuid_unique" on "customers" ("uuid");
CREATE UNIQUE INDEX "products_company_id_sku_unique" on "products" ("company_id", "sku");
CREATE INDEX "products_company_id_is_active_index" on "products" ("company_id", "is_active");
CREATE UNIQUE INDEX "products_uuid_unique" on "products" ("uuid");
CREATE UNIQUE INDEX "customer_orders_company_id_number_unique" on "customer_orders" ("company_id", "number");
CREATE INDEX "customer_orders_company_id_status_index" on "customer_orders" ("company_id", "status");
CREATE INDEX "customer_orders_customer_id_created_at_index" on "customer_orders" ("customer_id", "created_at");
CREATE UNIQUE INDEX "customer_orders_uuid_unique" on "customer_orders" ("uuid");
CREATE INDEX "customer_threads_company_id_desk_status_index" on "customer_threads" ("company_id", "desk", "status");
CREATE UNIQUE INDEX "customer_threads_uuid_unique" on "customer_threads" ("uuid");
CREATE INDEX "customer_thread_messages_thread_id_id_index" on "customer_thread_messages" ("thread_id", "id");
CREATE UNIQUE INDEX "customer_tickets_company_id_number_unique" on "customer_tickets" ("company_id", "number");
CREATE INDEX "customer_tickets_company_id_desk_status_index" on "customer_tickets" ("company_id", "desk", "status");
CREATE UNIQUE INDEX "customer_tickets_uuid_unique" on "customer_tickets" ("uuid");
CREATE INDEX "customer_ticket_messages_ticket_id_id_index" on "customer_ticket_messages" ("ticket_id", "id");

COMMIT;
